//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuestionario
    {
        public int IdCuestionario { get; set; }
        public int Pregunta01 { get; set; }
        public int Pregunta02 { get; set; }
        public int Pregunta03 { get; set; }
        public int Pregunta04 { get; set; }
        public int Pregunta05 { get; set; }
        public int Pregunta06 { get; set; }
        public int Pregunta07 { get; set; }
        public int Pregunta08 { get; set; }
        public int Pregunta09 { get; set; }
        public int Pregunta10 { get; set; }
        public int Pregunta11 { get; set; }
        public int Pregunta12 { get; set; }
        public int Pregunta13 { get; set; }
        public int Pregunta14 { get; set; }
        public int Pregunta15 { get; set; }
        public int Pregunta16 { get; set; }
        public int Pregunta17 { get; set; }
        public int Pregunta18 { get; set; }
        public int Pregunta19 { get; set; }
        public int Pregunta20 { get; set; }
        public int Pregunta21 { get; set; }
        public int Pregunta22 { get; set; }
        public int Pregunta23 { get; set; }
        public int Pregunta24 { get; set; }
        public int Pregunta25 { get; set; }
        public int Pregunta26 { get; set; }
        public int Pregunta27 { get; set; }
        public int Pregunta28 { get; set; }
        public int Pregunta29 { get; set; }
        public int Pregunta30 { get; set; }
        public int Pregunta31 { get; set; }
        public int Pregunta32 { get; set; }
        public int Pregunta33 { get; set; }
        public int Pregunta34 { get; set; }
        public int Pregunta35 { get; set; }
        public int Pregunta36 { get; set; }
        public int Pregunta37 { get; set; }
        public int Pregunta38 { get; set; }
        public int Pregunta39 { get; set; }
        public int Pregunta40 { get; set; }
        public int Pregunta41 { get; set; }
        public int Pregunta42 { get; set; }
        public int Pregunta43 { get; set; }
        public int Pregunta44 { get; set; }
        public int Pregunta45 { get; set; }
        public int Pregunta46 { get; set; }
        public int Pregunta47 { get; set; }
        public int Pregunta48 { get; set; }
        public int Pregunta49 { get; set; }
        public int Pregunta50 { get; set; }
        public int Pregunta51 { get; set; }
        public int Pregunta52 { get; set; }
        public int Pregunta53 { get; set; }
        public int Pregunta54 { get; set; }
        public int Pregunta55 { get; set; }
        public int Pregunta56 { get; set; }
        public int Pregunta57 { get; set; }
        public int Pregunta58 { get; set; }
        public int Pregunta59 { get; set; }
        public int Pregunta60 { get; set; }
        public int Pregunta61 { get; set; }
        public int Pregunta62 { get; set; }
        public int Pregunta63 { get; set; }
        public int Pregunta64 { get; set; }
        public bool ServicioCliente { get; set; }
        public Nullable<int> Pregunta65 { get; set; }
        public Nullable<int> Pregunta66 { get; set; }
        public Nullable<int> Pregunta67 { get; set; }
        public Nullable<int> Pregunta68 { get; set; }
        public bool JefeTrabajadores { get; set; }
        public Nullable<int> Pregunta69 { get; set; }
        public Nullable<int> Pregunta70 { get; set; }
        public Nullable<int> Pregunta71 { get; set; }
        public Nullable<int> Pregunta72 { get; set; }
    }
}
